# Generated by Django 2.1 on 2018-10-22 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=64)),
                ('course_code', models.CharField(max_length=20)),
                ('course_module', models.CharField(max_length=1000)),
                ('course_duration', models.CharField(choices=[('T', 'Time'), ('D', 'Day'), ('W', 'Weeks'), ('M', 'Months'), ('Y', 'Years')], default='T', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank='True', max_length=255)),
                ('document', models.FileField(upload_to='document')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=64)),
                ('host', models.CharField(max_length=64)),
                ('date_of_event', models.DateTimeField()),
                ('Events_View', models.CharField(choices=[('Web', 'webinars'), ('Con', 'Conference'), ('Seminar', 'Seminars')], default='Seminars', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity', models.CharField(choices=[('Jobs', 'Jobs'), ('Grants', 'Grants')], default='Jobs', max_length=20)),
                ('additionals', models.CharField(choices=[('Project', 'Project'), ('C.V', 'Curricullum Vitae')], default='C.V', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('U', 'Undergraduate'), ('M', 'Masters'), ('PHD', 'PHD'), ('StudyAbroad', 'StudyAbroad')], default='Undergraduate', max_length=20)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Success_storie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trainings_classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('date_of_training', models.DateTimeField()),
                ('type_of_training', models.CharField(choices=[('Career', 'Career Development'), ('Application', 'Procedure & Application'), ('Interview Skills', 'Interview Skills'), ('StudyAbroad', 'StudyAbroad')], default='career', max_length=20)),
                ('additional', models.CharField(choices=[('Project', 'Project'), ('C.V', 'Curricullum Vitae')], default='C.V', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('profile', models.CharField(max_length=1000)),
                ('Hobbies', models.CharField(max_length=100)),
                ('Sports', models.CharField(max_length=100)),
                ('Social_Media_accounts_names', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='success_storie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
