# Generated by Django 2.1 on 2018-10-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=64)),
                ('duration', models.DateTimeField(auto_now_add=True)),
                ('multiple_choices', models.CharField(max_length=100)),
            ],
        ),
    ]
